# -*- coding: utf-8 -*-
"""ML_Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11F2hgWuvTjUWs55VvYEh0sGKdRa2o2FD

Importing the dataset
"""

from sklearn.datasets import load_digits
import numpy as np
import pandas as pd

digits = load_digits()

df1 = pd.DataFrame(data = digits.data)

df1['species'] = digits.target

X = digits.data
Y = digits.target

"""Normalizing using Z score """

from sklearn.preprocessing import StandardScaler
X_scaled = StandardScaler().fit_transform(X)
X_scaled[:5]

"""Computing Covariance matrix"""

features = X_scaled.T
cov_matrix = np.cov(features)
print(cov_matrix)

"""Eigen value and vectors"""

values, vectors = np.linalg.eig(cov_matrix)
values[:5]

"""Choose the top K Eigen Values"""

explained_variances = []
for i in range(len(values)):
  explained_variances.append(values[i]/ np.sum(values))
print(explained_variances)

"""Construct reduced dataset"""

projected_1 = X_scaled.dot(vectors.T[0])
projected_2 = X_scaled.dot(vectors.T[1])
res = pd.DataFrame(projected_1, columns = ['PC1'])
res['PC2'] = projected_2
res['Y'] = Y
res.head()